version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    env_file: .env.postgres
    restart: always
    ports:
      - "3000:3000" # app
      - "5555:5555" # studio
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  migrate:
    build:
      context: .
      target: development
    env_file: .env.postgres
    command: pnpm db:migrate dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  seed:
    build:
      context: .
      target: development
    env_file: .env.postgres
    command: pnpm db:seed
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  integration-test:
    build:
      context: .
      target: development
    container_name: "e2e-test"
    env_file: .env.postgres.test
    command:
      - /bin/sh
      - -c
      - |
        pnpm db:migrate reset --force
        pnpm db:migrate dev
        pnpm test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

networks:
  default:
    name: podcodar-app

volumes:
  db:
