version: "3"

services:
  app:
    build: .
    env_file: .env.development
    ports:
      - "3000:3000" # app
      - "5555:5555" # studio
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env.development
    ports:
      - "5432:5432"

networks:
  default:
    name: podcodar-app
