name: Migrate Production

on:
  push:
    branches:
      - main

jobs:
  migrate_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate and Migrate
        run: npm run db:generate && npm run db:migrate deploy
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
