name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run integration tests
        run: |
          npm run e2e:up -d

      - name: Stop app and cleanup
        run: |
          npm run down
          docker-compose rm -f -s -v
