name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run integration tests
        id: integration-tests
        run: docker-compose run integration-test -it

      # - name: Set test status
      #   id: test-status
      #   run: |
      #     if [ ${{ steps.integration-tests.conclusion }} = "success" ]; then
      #       echo "Tests passed"
      #       echo "status=success" >> $GITHUB_OUTPUT
      #       echo "description=CI tests passed" >> $GITHUB_OUTPUT
      #     else
      #       echo "Tests failed"
      #       echo "status=failure" >> $GITHUB_OUTPUT
      #       echo "description=CI tests failed" >> $GITHUB_OUTPUT
      #     fi

      - name: Stop app and cleanup
        run: |
          npm run down
          docker-compose rm -f -s -v

      # - name: Set GitHub status
      #   if: always()
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const status = "${{ steps.test-status.outputs.status }}";
      #       const description = "${{ steps.test-status.outputs.description }}";
      #       github.repos.createCommitStatus({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         sha: context.sha,
      #         state: status,
      #         description: description,
      #         context: 'Integration Tests'
      #       })
