name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "podcodar"
          POSTGRES_PASSWORD: "my-password"
          POSTGRES_DB: "podcodar-app-test-db"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and start app
        run: |
          npm ci
          npm run build
          npm run start &

      - name: Wait for app to start
        run: npm run wait-for-app

      - name: Install dependencies
        run: npm ci --production=false

      - name: Run integration tests
        run: npm run e2e:up

      - name: Stop app and cleanup
        run: |
          npm run down
          docker-compose rm -f -s -v
